version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: proto14-app
    ports:
      - "3000:3000"
    volumes:
      - ./proto14-platform:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    command: npm run dev
    networks:
      - proto14-network

  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proto14-app-prod
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    networks:
      - proto14-network
    profiles:
      - production

networks:
  proto14-network:
    driver: bridge